//A2Z Issue Tracking  Service
[
'service_category_id' => 16,
'namespace' => 'App\Http\Controllers\Admin',
'controller' => 'IssueTrackingController',
'method' => 'GET',
'action' => 'index',
'created_at' => Carbon::now()->toDateTimeString(),
'updated_at' => Carbon::now()->toDateTimeString(),
],
[
'service_category_id' => 16,
'namespace' => 'App\Http\Controllers\Admin',
'controller' => 'IssueTrackingController',
'method' => 'GET',
'action' => 'create',
'created_at' => Carbon::now()->toDateTimeString(),
'updated_at' => Carbon::now()->toDateTimeString(),
],
[
'service_category_id' => 16,
'namespace' => 'App\Http\Controllers\Admin',
'controller' => 'IssueTrackingController',
'method' => 'GET',
'action' => 'show',
'created_at' => Carbon::now()->toDateTimeString(),
'updated_at' => Carbon::now()->toDateTimeString(),
],
[
'service_category_id' => 16,
'namespace' => 'App\Http\Controllers\Admin',
'controller' => 'IssueTrackingController',
'method' => 'GET',
'action' => 'edit',
'created_at' => Carbon::now()->toDateTimeString(),
'updated_at' => Carbon::now()->toDateTimeString(),
],
[
'service_category_id' => 16,
'namespace' => 'App\Http\Controllers\Admin',
'controller' => 'IssueTrackingController',
'method' => 'POST',
'action' => 'store',
'created_at' => Carbon::now()->toDateTimeString(),
'updated_at' => Carbon::now()->toDateTimeString(),
],
[
'service_category_id' => 16,
'namespace' => 'App\Http\Controllers\Admin',
'controller' => 'IssueTrackingController',
'method' => 'PUT',
'action' => 'update',
'created_at' => Carbon::now()->toDateTimeString(),
'updated_at' => Carbon::now()->toDateTimeString(),
],
[
'service_category_id' => 16,
'namespace' => 'App\Http\Controllers\Admin',
'controller' => 'IssueTrackingController',
'method' => 'DELETE',
'action' => 'destroy',
'created_at' => Carbon::now()->toDateTimeString(),
'updated_at' => Carbon::now()->toDateTimeString(),
],