<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ServiceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $service = [
            [
                  'service_category_id' => 1,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'DashboardController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              //Roles Service
              [
                  'service_category_id' => 2,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 2,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 2,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 2,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 2,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 2,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 2,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //Users Service
              [
                  'service_category_id' => 3,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 3,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 3,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 3,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 3,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 3,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 3,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],


              //Department Service
              [
                  'service_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'DepartmentController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'DepartmentController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'DepartmentController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'DepartmentController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'DepartmentController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'DepartmentController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'DepartmentController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //Authors Service
              [
                  'service_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'AuthorController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'AuthorController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'AuthorController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'AuthorController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'AuthorController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'AuthorController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'AuthorController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //Publisher Service
              [
                  'service_category_id' => 6,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'PublisherController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 6,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'PublisherController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 6,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'PublisherController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 6,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'PublisherController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 6,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'PublisherController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 6,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'PublisherController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 6,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'PublisherController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //ServiceCategory Service
              [
                  'service_category_id' => 7,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ServiceCategoryController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 7,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ServiceCategoryController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 7,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ServiceCategoryController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 7,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ServiceCategoryController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 7,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ServiceCategoryController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 7,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ServiceCategoryController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 7,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ServiceCategoryController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //Item Standard Number Service
              [
                  'service_category_id' => 8,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemStandardNumberController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 8,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemStandardNumberController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 8,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemStandardNumberController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 8,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemStandardNumberController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 8,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemStandardNumberController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 8,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemStandardNumberController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 8,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemStandardNumberController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //Item Service
              [
                  'service_category_id' => 9,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 9,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 9,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 9,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 9,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 9,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 9,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'ItemController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //Sister Concern  Service
              [
                  'service_category_id' => 10,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'SisterConcernController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 10,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'SisterConcernController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 10,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'SisterConcernController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 10,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'SisterConcernController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 10,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'SisterConcernController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 10,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'SisterConcernController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 10,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'SisterConcernController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //Ratings  Service
              [
                  'service_category_id' => 11,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RatingController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 11,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RatingController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 11,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RatingController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 11,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RatingController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 11,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RatingController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 11,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RatingController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 11,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RatingController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],


              //A2Z Type  Service
              [
                  'service_category_id' => 12,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zTypeController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 12,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zTypeController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 12,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zTypeController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 12,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zTypeController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 12,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zTypeController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 12,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zTypeController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 12,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zTypeController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //A2Z Vendor  Service
              [
                  'service_category_id' => 13,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zVendorController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 13,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zVendorController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 13,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zVendorController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 13,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zVendorController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 13,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zVendorController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 13,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zVendorController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 13,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zVendorController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //A2Z Subject  Service
              [
                  'service_category_id' => 14,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zSubjectController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 14,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zSubjectController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 14,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zSubjectController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 14,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zSubjectController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 14,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zSubjectController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 14,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zSubjectController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 14,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zSubjectController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //A2Z Database  Service
              [
                  'service_category_id' => 15,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zDatabaseController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 15,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zDatabaseController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 15,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zDatabaseController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 15,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zDatabaseController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 15,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zDatabaseController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 15,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zDatabaseController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 15,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'A2zDatabaseController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //A2Z Issue Tracking  Service
              [
                  'service_category_id' => 16,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'IssueTrackingController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 16,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'IssueTrackingController',
                  'method' => 'GET',
                  'action' => 'create',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 16,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'IssueTrackingController',
                  'method' => 'GET',
                  'action' => 'show',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 16,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'IssueTrackingController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 16,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'IssueTrackingController',
                  'method' => 'POST',
                  'action' => 'store',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 16,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'IssueTrackingController',
                  'method' => 'POST',
                  'action' => 'feedback',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 16,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'IssueTrackingController',
                  'method' => 'POST',
                  'action' => 'assignTo',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 16,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'IssueTrackingController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 16,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'IssueTrackingController',
                  'method' => 'PUT',
                  'action' => 'rating',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'service_category_id' => 16,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'IssueTrackingController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //Audit logs
              [
                  'service_category_id' => 17,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'AuditLogController',
                  'method' => 'GET',
                  'action' => 'index',
                  'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

            //Item Category
            [
                'service_category_id' => 18,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoryController',
                'method' => 'GET',
                'action' => 'index',
                'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 18,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoryController',
                'method' => 'GET',
                'action' => 'create',
                'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 18,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoryController',
                'method' => 'GET',
                'action' => 'show',
                'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 18,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'IssueTrackingController',
                'method' => 'GET',
                'action' => 'edit',
                'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 18,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoryController',
                'method' => 'POST',
                'action' => 'store',
                'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            [
                'service_category_id' => 18,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoryController',
                'method' => 'PUT',
                'action' => 'update',
                'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 18,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoryController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'displayName'=>'',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],


            //Report Controller
            [
                'service_category_id' => 19,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ReportController',
                'method' => 'GET',
                'action' => 'index',
                'displayName'=>'Show report type page',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            [
                'service_category_id' => 19,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ReportController',
                'method' => 'GET',
                'action' => 'uploadStatistics',
                'displayName'=>'Open Upload Statistics report page',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 19,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ReportController',
                'method' => 'POST',
                'action' => 'uploadStatistics',
                'displayName'=>'Generate Upload Statistics report',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            [
                'service_category_id' => 19,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ReportController',
                'method' => 'GET',
                'action' => 'downloadStatistics',
                'displayName'=>'Open download statistics report page',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            [
                'service_category_id' => 19,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ReportController',
                'method' => 'GET',
                'action' => 'downloadStatistics',
                'displayName'=>'Generate download statistics report',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            //Semester
            [
                'service_category_id' => 20,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SemesterController',
                'method' => 'GET',
                'action' => 'index',
                'displayName'=>'Display All Semester',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 20,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SemesterController',
                'method' => 'GET',
                'action' => 'create',
                'displayName'=>'new semester form',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 20,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SemesterController',
                'method' => 'GET',
                'action' => 'show',
                'displayName'=>'single semester view',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 20,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SemesterController',
                'method' => 'GET',
                'action' => 'edit',
                'displayName'=>'edit form semester',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 20,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SemesterController',
                'method' => 'POST',
                'action' => 'store',
                'displayName'=>'new semester store in database',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            [
                'service_category_id' => 20,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SemesterController',
                'method' => 'PUT',
                'action' => 'update',
                'displayName'=>'semester update',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 20,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SemesterController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'displayName'=>'delete a semester',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            //Item Category
            [
                'service_category_id' => 21,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SupervisorController',
                'method' => 'GET',
                'action' => 'index',
                'displayName'=>'List of supervisor',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 21,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SupervisorController',
                'method' => 'GET',
                'action' => 'create',
                'displayName'=>'supervisor form open',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 21,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SupervisorController',
                'method' => 'GET',
                'action' => 'show',
                'displayName'=>'single supervisor view',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 21,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SupervisorController',
                'method' => 'GET',
                'action' => 'edit',
                'displayName'=>'supervisor edit form open',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 21,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SupervisorController',
                'method' => 'POST',
                'action' => 'store',
                'displayName'=>'supervisor store in database',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            [
                'service_category_id' => 21,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SupervisorController',
                'method' => 'PUT',
                'action' => 'update',
                'displayName'=>'Update supervisor',

                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'service_category_id' => 21,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SupervisorController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'displayName'=>'Delete a supervisor',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
        ];
        DB::table('services')->insert($service);


    }
}
